# 全局配置文件
# Site settings
title: Yezhaoyan Blog              #博客的标题
SEOTitle: 叶昭言的博客 | ZY Blog    #浏览器显示的标签
header-img: img/post-bg-desk.jpg   #显示在首页的背景图片
email: ye_zhaoyan@163.com
description: "My blog"                  #网站介绍
keyword: ""
url: "http://yezhaoyan.github.io"          # your host, for absolute URL 博客地址
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yezhaoyan/yezhaoyan.github.io.git" # you code repository

# Sidebar settings 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "格言!"      #侧边栏，想说啥呢
sidebar-avatar: /img/avatar-m      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     
zhihu_username:     
github_username:    
facebook_username:  
jianshu_username:   
twitter_username:  




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统  博客中使用的是Disqus评价系统。在国内加载慢，所以用新集成的Gitalk评价插件，如下
# Disqus（https://disqus.com/）
# disqus_username: 

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: yezhaoyan.github.io    #仓库名称
  owner: yezhaoyan    #github用户名
  admin: yezhaoyan
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id:      #没有国内手机号，注册不了！！

# Google Analytics
ga_track_id: 'UA-137475981-1'            # Format: UA-xxxxxx-xx  Ye Zhaoyan Blog
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends                    想加的时候再加吧
#friends: [
#  {
#        title: "WY",
#       href: "http://zhengwuyang.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
